MUD/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_character , name="view_character"),
    path('edit', views.edit_character , name="edit_character"),
    path('inventory', views.manage_inventory, name="manage_inventory"),
    path('update_item', views.update_item, name="update_item"),
    path('view_items', views.view_items, name="view_items"),
    path('buy_item', views.buy_item, name="buy_item"),
    path('sell_item', views.sell_item, name="sell_item"),
    path('view_shop', views.view_shop, name="view_shop"),
]

PersonalWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from PersonalWebsite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('MUD/', include('MUD.urls')),
    path('checkout/', include('checkout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MUD/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth import get_user_model

from . import defaultValues
from .utils import Slot, ItemType, ItemRarity


class Item(models.Model):

    name = models.CharField(max_length=254)

    image_url = models.URLField(max_length=1024, null=True, blank=True)

    image = models.ImageField(
        upload_to="items", max_length=1204, null=True, blank=True
    )

    item_type = models.CharField(
        default=ItemType.SHIELD, choices=ItemType.choices, max_length=50
    )

    slot = models.CharField(
        default=Slot.OFF_HAND, choices=Slot.choices, max_length=50
    )

    width = models.IntegerField(default=1, validators=[MinValueValidator(1)])

    height = models.IntegerField(default=1, validators=[MinValueValidator(1)])

    description = models.TextField()

    cost = models.DecimalField(max_digits=4, decimal_places=0)

    rarity = models.CharField(
        default=ItemRarity.COMMON, choices=ItemRarity.choices, max_length=50
    )

    def __str__(self):
        return f"{self.id} - {self.name} "


class ItemSettings(models.Model):

    character = models.ForeignKey(
        "Character",
        on_delete=models.CASCADE,
        related_name="items",
        related_query_name="items",
    )

    item = models.ForeignKey(
        "Item",
        on_delete=models.CASCADE,
        related_name="settings",
        related_query_name="settings",
    )

    lastSpaceIndex = models.CharField(default="-1", max_length=2)

    currentSpaceIndex = models.CharField(default="-1", max_length=2)

    equipped = models.BooleanField(default=False)

    def __str__(self):
        return f" {self.character.owner.username} - {self.item.name} - {self.equipped}"


class Character(models.Model):
    """ Represents each chatter's character """

    owner = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="owner"
    )

    inventory_size = models.IntegerField(
        validators=[
            MinValueValidator(defaultValues.MIN_INVENTORY_SIZE),
            MaxValueValidator(defaultValues.MAX_INVENTORY_SIZE),
        ],
        default=defaultValues.DEFAULT_INVENTORY_SIZE,
    )

    points = models.IntegerField(
        validators=[
            MinValueValidator(defaultValues.MIN_POINTS_VALUE),
            MaxValueValidator(defaultValues.MAX_POINTS_VALUE),
        ],
        default=defaultValues.DEFAULT_POINTS_VALUE,
    )

    gold = models.IntegerField(
        validators=[
            MinValueValidator(defaultValues.MIN_GOLD_VALUE),
            MaxValueValidator(defaultValues.MAX_GOLD_VALUE),
        ],
        default=defaultValues.DEFAULT_GOLD_VALUE,
    )

    hp = models.IntegerField(
        validators=[
            MinValueValidator(defaultValues.MIN_HP_VALUE),
            MaxValueValidator(defaultValues.MAX_HP_VALUE),
        ],
        default=defaultValues.DEFAULT_HP_VALUE,
    )

    mp = models.IntegerField(
        validators=[
            MinValueValidator(defaultValues.MIN_MP_VALUE),
            MaxValueValidator(defaultValues.MAX_MP_VALUE),
        ],
        default=defaultValues.DEFAULT_MP_VALUE,
    )

    # Controls movement speed
    agility = models.IntegerField(
        validators=[
            MinValueValidator(defaultValues.MIN_AGILITY_VALUE),
            MaxValueValidator(defaultValues.MAX_AGILITY_VALUE),
        ],
        default=defaultValues.DEFAULT_AGILITY_VALUE,
    )

    # Dodge / handling of certain weapons
    dexterity = models.IntegerField(
        validators=[
            MinValueValidator(defaultValues.MIN_DEXTERITY_VALUE),
            MaxValueValidator(defaultValues.MAX_DEXTERITY_VALUE),
        ],
        default=defaultValues.DEFAULT_DEXTERITY_VALUE,
    )

    # Damage / handling of certain weapons
    strength = models.IntegerField(
        validators=[
            MinValueValidator(defaultValues.MIN_STRENGTH_VALUE),
            MaxValueValidator(defaultValues.MAX_STRENGTH_VALUE),
        ],
        default=defaultValues.DEFAULT_STRENGTH_VALUE,
    )

    def __str__(self):
        return f"{self.owner.username}'s character"

MUD/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.serializers import serialize
from django.shortcuts import HttpResponse, redirect, render, reverse, get_object_or_404
from django.db.models import Q

from .forms import DisplayCharacterForm, EditCharacterForm
from .helpers import (get_character, get_items_to_display,
                      validate_character_form)
from .models import Character, Item, ItemSettings
from .utils import ItemRarity, ItemType, Slot


def view_shop(request):
    """
    Display a view that allows the user to buy gold

    """
    if request.POST:
        name = request.POST['bundle_name']
        if name:
            if name == "small":
                price = 2.99
            elif name == "medium":
                price = 5.99
            else:
                price = 9.99

            request.session['bundle_name'] = name
            request.session['bundle_price'] = price

            return redirect(reverse('checkout'))

    return render(request, "buygold.html")

def view_items(request):
    """
    Displays all the items available to the user.
    Filters out items that the user already owns

    """
    character = get_character(request.user.username)
    context = {}
    items = Item.objects.all()

    if request.GET:
        if 'rarity' in request.GET:
            rarities = request.GET['rarity']
            if rarities:
                rarities = [rarity.lower() for rarity in rarities.split(',')]
                items = items.filter(rarity__in=rarities)

        if 'type' in request.GET:
            types = request.GET['type']
            if types:
                types = [types.lower() for type in types.split(',')]
                items = items.filter(item_type__in=types)

        if 'slot' in request.GET:
            slots = request.GET['slots']
            if slots:
                slots = [slot.lower() for slots in slots.split(',')]
                items = items.filter(slot__in=slots)

        if 'q' in request.GET:
            query = request.GET['q']
            if  query:
                queries = Q(name__icontains=query) | Q(description__icontains=query) | Q(rarity__icontains=query) | Q(item_type__icontains=query)
                items  = items.filter(queries)

    if character:
        character_items = character.items.values_list("item__name",flat=True)
        context["character_items"] = character_items
        context["character_gold"] = character.gold

    context["items"] = items

    context["item_types"] = ItemType.labels
    context["item_slots"] = Slot.labels
    context["item_rarities"] = ItemRarity.labels

    return render(request, "Item/index.html", context)

@login_required
def sell_item(request):
    """
    Lets a user sell an item if they own it. For half of the buy price.

    """
    if request.method == "GET":
        return redirect(reverse("view_items"))

    character = get_character(request.user.username)
    if character:
        item_name = request.POST["item_name"]
        if ItemSettings.objects.filter(character=character, item__name=item_name).exists():
            character_item = ItemSettings.objects.get(character=character, item__name=item_name)
            item_cost = get_object_or_404(Item,name=item_name).cost
            refund = round(item_cost/2) if round(item_cost/2) > 0 else 1
            character_item.delete()
            character.gold += refund
            character.save()
            messages.add_message(request, messages.SUCCESS, f"Sold {item_name} for {refund} gold")
            return redirect(reverse("view_items"))

    messages.add_message(request, messages.WARNING, f"Couldn't sell {item_name}")
    return redirect(reverse("view_items"))


@login_required
def buy_item(request):
    """
    Attempts to buy an item for a character. Succeeds if the character
    has enough gold and doesn't already own the item

    """
    if request.method == "GET":
        return redirect(reverse("view_items"))

    item_name = request.POST["item_name"]
    item = get_object_or_404(Item, name=item_name)
    character = get_object_or_404(Character,owner__username = request.user.username)
    context = {}
    items = Item.objects.all()

    context['items'] = items
    context['character_gold'] = character.gold

    character_items = character.items.values_list("item__name",flat=True)
    context['character_items'] = character_items
    if character.gold >= item.cost:
        obj, created = ItemSettings.objects.get_or_create(
            character=character, item=item
        )

        if not created:
            messages.add_message(
                request, messages.INFO, f"You already own {item_name}"
            )
            return render(request, "Item/index.html", context)

        character.gold -= item.cost
        context['character_gold'] = character.gold
        character.save()
    else:
        messages.add_message(
            request, messages.INFO, f"Not enough gold to buy {item_name}"
        )
        return render(request, "Item/index.html", context)

    character_items = character.items.values_list("item__name",flat=True)
    context['character_items'] = character_items

    messages.add_message(request, messages.SUCCESS, f"Bought {item_name}")
    return render(request, "Item/index.html", context)


@login_required
def view_character(request):
    """
    Allows the user to view or edit their character.
    """

    can_edit = False

    character = get_character(request.user.username)
    if not character:
        character = Character(owner=request.user)
        character.save()

    if character.points > 0:
        can_edit = True

    character_form = DisplayCharacterForm(instance=character)
    context = {"character_form": character_form, "can_edit": can_edit}

    return render(request, "Character/index.html", context)


@login_required
def edit_character(request):
    """
    Allows the user to spend points upgrading their character

    """
    character = get_character(request.user.username)
    if not character:
        return redirect(reverse("view_character"))

    if character.points == 0:
        return redirect(reverse("view_character"))

    character_form = EditCharacterForm(
        request.POST or None, instance=character
    )

    if request.method == "POST":
        if character_form.has_changed():
            if character_form.is_valid():
                if validate_character_form(
                    request.POST, request.user.username
                ):
                    character_form.save()
                    if character.points == 0:
                        return redirect(reverse("view_character"))

    context = {"character_form": character_form, "respec": False}

    return render(request, "Character/editCharacter.html", context)


@login_required
def manage_inventory(request):
    """
    Allows the user to manage their inventory and items.

    """

    character = get_character(request.user.username)
    if not character:
        return redirect(reverse("view_character"))

    character_items = list(character.items.all().order_by("item_id"))

    item_ids = [ItemSettings.item_id for ItemSettings in character_items]

    item_data = list(
        Item.objects.filter(pk__in=item_ids)
        .order_by("id")
        .values(
            "name",
            "image",
            "item_type",
            "slot",
            "width",
            "height",
            "rarity",
        )
    )

    for index, item in enumerate(item_data):
        item["lastSpaceIndex"] = character_items[index].lastSpaceIndex
        item["currentSpaceIndex"] = character_items[index].currentSpaceIndex
        item["equipped"] = character_items[index].equipped

    context = {
        "inventory_size": character.inventory_size,
        "items": item_data,
    }

    return render(request, "Character/inventory.html", context)


@login_required
def update_item(request):
    """
    Expects to recieve a list of dictionaries.
    The dictionary needs to have one key of "name" that is the item to update.
    The rest of the key,value pairs are presumed to be settings for the item.
    """
    character = get_character(request.user.username)
    if not character:
        return redirect(reverse("view_character"))

    if request.method == "POST":
        data = json.load(request)["item_data"]

        for item in data:
            itemsettings = ItemSettings.objects.get(
                item__name=item["name"], character_id=character.id
            )

            if itemsettings:
                item.pop("name")
                for attribute, value in item.items():
                    setattr(itemsettings, attribute, value)
                itemsettings.save()
            else:
                return HttpResponse(status=404)

        return HttpResponse(200)
    else:
        return redirect(reverse("manage_inventory"))

MUD/templates/includes/DisplayCharacterForm.html
<form id="displayCharacterForm" accept-charset="utf-8">
  <!-- POINTS -->
  <fieldset class="row trait-container">
    <div class="col-12">
      <legend id="PointsTitle" class="trait-title">What can I spend</legend>
    <div class="col-12 trait">
      <p id="HPTitle" class="trait-title">Points</p>
      <div class="input-group justify-content-center">
        {{character_form.points | as_crispy_field}}
      </div>
    </div>
    <div class="col-12 trait">
      <p id="GoldTitle" class="trait-title">Gold</p>
      <div class="input-group justify-content-center">
        {{ character_form.gold | as_crispy_field }}
      </div>
    </div>
  </fieldset>
  <!-- /POINTS -->

  <!-- CORE -->
  <fieldset class="row trait-container">
    <div class="col-12">
      <legend>Core</legend>
    </div>
    <div class="col-12 trait">
      <p id="HPTitle" class="trait-title">HP</p>
      <div class="input-group justify-content-center">
        {{ character_form.hp | as_crispy_field }}
      </div>
    </div>

    <div class="trait">
      <p id="MPTitle" class="trait-title">MP</p>
      <div class="input-group justify-content-center">
        {{ character_form.mp | as_crispy_field }}
      </div>
    </div>
  </fieldset>
  <!-- /CORE -->

  <fieldset class="row trait-container">
    <div class="col-12">
      <legend>Traits</legend>
      <div class="trait">
        <p id="StrengthTitle" class="trait-title">Strength</p>
        <div class="input-group justify-content-center">
          {{ character_form.strength | as_crispy_field }}
        </div>
      </div>
      <div class="trait">
        <p id="AgilityTitle" class="trait-title">Agility</p>
        <div class="input-group justify-content-center">
          {{ character_form.agility | as_crispy_field }}
        </div>
      </div>
      <div class="trait">
        <p id="DexterityTitle" class="trait-title">Dexterity</p>
        <div class="input-group justify-content-center">
          {{ character_form.dexterity | as_crispy_field }}
        </div>
      </div>
    </div>
  </fieldset>
</form>

MUD/templates/includes/EditCharacterForm.html
<form
  id="editCharacterForm"
  action="{% url 'edit_character' %}"
  method="POST"
  accept-charset="utf-8"
>
  {% csrf_token %}

  <fieldset class="row trait-container">
    <div class="col-12 trait">
      <legend class="trait-title" id="PointsTitle">Points</legend>
      <div class="input-group">{{character_form.points | as_crispy_field}}</div>
    </div>
  </fieldset>

  <!-- CORE -->
  <fieldset class="row trait-container">
    <!-- HP -->
    <div class="col-12">
      <legend>Core</legend>
    </div>

    <div class="col-12 trait">
      <p class="trait-title" id="HPTitle">HP</p>
      <div class="input-group">
        <button class="btn decButton" data-target="id_hp" {% if respec == False %} disabled {% endif %}>
          <i class="fas fa-minus"></i>
        </button>
        {{character_form.hp | as_crispy_field }}
        <button class="btn incButton" data-target="id_hp">
          <i class="fas fa-plus"></i>
        </button>
      </div>
    </div>
    <!-- /HP -->

    <!-- MP -->
    <div class="col-12 trait">
      <p  class="trait-title" id="MPTitle" class="mb-0">MP</p>
      <div class="input-group">
        <button class="btn decButton" data-target="id_mp" {% if respec == False %} disabled {% endif %}>
          <i class="fas fa-minus"></i>
        </button>
        {{character_form.mp | as_crispy_field }}
        <button class="btn incButton" data-target="id_mp">
          <i class="fas fa-plus"></i>
        </button>
      </div>
    </div>
    <!-- /MP -->
  </fieldset>
  <!-- /CORE -->

  <!-- TRAITS -->
  <fieldset class="row trait-container">
    <div class="col-12 trait">
      <legend>Traits</legend>
    </div>

    <!-- STR -->
    <div class="col-12 trait">
      <p class="trait-title" id="StrengthTitle">Strength</p>
      <div class="input-group justify-content-center">
        <button class="btn decButton" data-target="id_strength" {% if respec == False %} disabled {% endif %}>
          <i class="fas fa-minus"></i>
        </button>
        {{ character_form.strength | as_crispy_field }}
        <button class="btn incButton" data-target="id_strength">
          <i class="fas fa-plus"></i>
        </button>
      </div>
    </div>
    <!-- /STR -->

    <!-- AGI -->
    <div class="col-12 trait">
      <p id="AgilityTitle" class="trait-title">Agility</p>
      <div class="input-group justify-content-center">
        <button class="btn decButton" data-target="id_agility" {% if respec == False %} disabled {% endif %}>
          <i class="fas fa-minus"></i>
        </button>
        {{character_form.agility | as_crispy_field }}
        <button class="btn incButton" data-target="id_agility">
          <i class="fas fa-plus"></i>
        </button>
      </div>
    </div>
    <!-- /AGI -->

    <!-- DEX -->
    <div class="col-12 trait">
      <p id="DexterityTitle" class="trait-title">Dexterity</p>
      <div class="input-group justify-content-center">
        <button class="btn decButton" data-target="id_dexterity" {% if respec == False %} disabled {% endif %}>
          <i class="fas fa-minus"></i>
        </button>
        {{character_form.dexterity | as_crispy_field }}
        <button class="btn incButton" data-target="id_dexterity">
          <i class="fas fa-plus"></i>
        </button>
      </div>
  </fieldset>
<div id="buttons" class="row btn-group">
    <div class="col-12">
    <button class="btn" type="save">Save</button>
    <button class="btn" type="reset">Reset</button>
    </div>
</div>
</form>

MUD/templates/includes/itemCard.html
{% load mathfilters %}

<div class="col">
  <div class="card item-card" style="width: 18rem">
    <div class="{{item.rarity}}">
      <div class="img-wrapper">
        <img
          src="{{MEDIA_URL}}{{item.image}}"
          class="card-img-top"
          alt="{{item.name}}"
        />
      </div>
    </div>

    <div class="card-body">
      <h5 class="card-title">{{item.name}}</h5>
      <p class="card-text">{{item.description}}</p>
    </div>

    <div class="card-body">
      <table class="table table-hover table-borderless p-4">
        <tbody>
          <tr scope="row">
            <td class="text-start">
              <strong> Slot: </strong>
            </td>
            <td class="text-end">{{item.get_slot_display}}</td>
          </tr>
          <tr scope="row">
            <td class="text-start">
              <strong> Item Type: </strong>
            </td>
            <td class="text-end">{{item.get_item_type_display}}</td>
          </tr>
          <tr scope="row">
            <td class="text-start">
              <strong> Rarity: </strong>
            </td>
            <td class="text-end">
              {{item.get_rarity_display}}
            </td>
          </tr>
          <tr scope="row">
            <td class="text-start">
              <strong> Cost: </strong>
            </td>
            <td id="{{item.name}}Cost" class="text-end">
              {{item.cost}} Gold coin{%if item.cost > 1 %}s{% endif %}
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="card-footer">
        {% if user.is_authenticated %}
            {% if item.name in character_items %}
                <form method="POST" action="{%url 'sell_item'%}">
                {% csrf_token %}
                <input type="hidden" name="item_name" value="{{item.name}}">
                <button class="btn" type="submit">Sell for
                    {% if item.cost|intdiv:2 == 0 %}
                    1
                    {% else %}
                    {{ item.cost|intdiv:2}}
                    {% endif %}
                </button>
                </form>
            {% else %}
                <form method="POST" action="{%url 'buy_item'%}">
                {% csrf_token %}
                <input type="hidden" name="item_name" value="{{item.name}}">
                <button class="btn" type="submit">Buy</button>
                </form>
            {% endif %}
        {% endif %}
    </div>
  </div>
</div>